import streamlit as st
import google.generativeai as genai
from pypdf import PdfReader
from docx import Document
from io import BytesIO
from duckduckgo_search import DDGS
from datetime import datetime, timedelta, date
import time
import pandas as pd
import base64
import sys
import psycopg2 

# ==========================================================
# 1. CONFIGURAÇÃO VISUAL - CYBER THEME
# ==========================================================
st.set_page_config(
    page_title="LegalHub Elite v8.5", 
    page_icon="⚖️", 
    layout="wide",
    initial_sidebar_state="expanded"
)

# ==========================================================
# 2. CONEXÃO COM BANCO DE DADOS (CORRIGIDA E BLINDADA)
# ==========================================================
try:
    DB_URI = st.secrets["DB_URI"]
    API_KEY_FIXA = st.secrets["GOOGLE_API_KEY"]
    CONEXAO_NUVEM = True
except:
    # Se não tiver secrets, avisa o modo offline mas não quebra
    DB_URI = "" 
    API_KEY_FIXA = ""
    CONEXAO_NUVEM = False

def get_db_connection():
    if CONEXAO_NUVEM:
        try:
            return psycopg2.connect(DB_URI)
        except:
            return None
    else:
        import sqlite3
        return sqlite3.connect(':memory:', check_same_thread=False)

def run_query(query, params=(), return_data=False):
    conn = get_db_connection()
    if conn is None: return None # Proteção contra falha de conexão
    
    try:
        c = conn.cursor()
        if not CONEXAO_NUVEM: query = query.replace('%s', '?') # Adapta para SQLite se offline
        
        c.execute(query, params)
        
        if return_data:
            data = c.fetchall()
            col_names = [desc[0] for desc in c.description] if c.description else []
            conn.close()
            return pd.DataFrame(data, columns=col_names)
        else:
            conn.commit()
            conn.close()
            return True
    except Exception as e:
        if conn: conn.close()
        # st.error(f"Erro DB: {e}") # Debug silencioso
        return None

# --- CRIAÇÃO DE TABELAS AO INICIAR (SEGURANÇA) ---
# Isso garante que o banco exista antes de tentar logar
if not CONEXAO_NUVEM:
    try:
        import sqlite3
        conn = sqlite3.connect(':memory:', check_same_thread=False)
        c = conn.cursor()
        c.execute("CREATE TABLE IF NOT EXISTS usuarios (username TEXT PRIMARY KEY, senha TEXT, escritorio TEXT, email_oab TEXT, creditos INTEGER DEFAULT 10, plano TEXT DEFAULT 'starter')")
        c.execute("CREATE TABLE IF NOT EXISTS documentos (id INTEGER PRIMARY KEY AUTOINCREMENT, escritorio TEXT, data_criacao TEXT, cliente TEXT, area TEXT, tipo TEXT, conteudo TEXT)")
        c.execute("INSERT OR IGNORE INTO usuarios (username, senha, escritorio) VALUES ('admin', 'admin', 'Master Office')")
        conn.commit()
    except: pass
else:
    # Postgres Nuvem
    run_query("CREATE TABLE IF NOT EXISTS usuarios (username TEXT PRIMARY KEY, senha TEXT, escritorio TEXT, email_oab TEXT, creditos INTEGER DEFAULT 10, plano TEXT DEFAULT 'starter')")
    run_query("CREATE TABLE IF NOT EXISTS documentos (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, escritorio TEXT, data_criacao TEXT, cliente TEXT, area TEXT, tipo TEXT, conteudo TEXT)")
    # Garante admin
    run_query("INSERT INTO usuarios (username, senha, escritorio, email_oab, creditos, plano) VALUES (%s, %s, %s, %s, %s, %s) ON CONFLICT (username) DO NOTHING", ('admin', 'admin', 'Master Office', 'adm@lh.com', 9999, 'full'))


# ==========================================================
# 3. FUNÇÕES (IA, PDF, WORD, ANTI-ALUCINAÇÃO)
# ==========================================================
def get_base64_of_bin_file(bin_file):
    try:
        with open(bin_file, 'rb') as f: data = f.read()
        return base64.b64encode(data).decode()
    except FileNotFoundError: return None

def gerar_word(texto):
    doc = Document()
    for p in texto.split('\n'):
        if p.strip(): doc.add_paragraph(p)
    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf

def extrair_texto_pdf(arquivo):
    try: return "".join([p.extract_text() for p in PdfReader(arquivo).pages])
    except: return ""

def buscar_contexto_juridico(tema, area):
    fontes = {
        "Criminal": "site:stj.jus.br OR site:stf.jus.br OR site:conjur.com.br",
        "Trabalhista": "site:tst.jus.br OR site:csjt.jus.br OR site:trtsp.jus.br",
        "Tributário": "site:carf.fazenda.gov.br OR site:stj.jus.br",
        "Previdenciário": "site:gov.br/inss OR site:trf3.jus.br",
        "Cível": "site:stj.jus.br OR site:tjsp.jus.br OR site:ibdfam.org.br"
    }
    site_query = fontes.get(area, "site:jusbrasil.com.br")
    query = f"{tema} jurisprudência {site_query}"
    try:
        with DDGS() as ddgs:
            results = list(ddgs.text(query, region="br-pt", max_results=3))
            if results:
                texto_res = "\n".join([f"- {r['title']}: {r['body']} (Fonte: {r['href']})" for r in results])
                return f"\n\n[JURISPRUDÊNCIA REAL ENCONTRADA]:\n{texto_res}"
    except: pass
    return "\n\n[NENHUMA JURISPRUDÊNCIA ESPECÍFICA ENCONTRADA NOS CANAIS OFICIAIS]"

def tentar_gerar_conteudo(prompt, api_key_val):
    chave = api_key_val if api_key_val else API_KEY_FIXA
    if not chave: return "⚠️ Erro: API Key não configurada."
    genai.configure(api_key=chave)
    try:
        model = genai.GenerativeModel("gemini-1.5-flash")
        return model.generate_content(prompt).text
    except Exception as e: return f"❌ Erro IA: {str(e)}"

# --- CÁLCULO TRABALHISTA COMPLETO ---
def calcular_rescisao_completa(admissao, demissao, salario_base, motivo, saldo_fgts, ferias_vencidas, aviso_tipo, grau_insalubridade, tem_periculosidade):
    formato = "%Y-%m-%d"
    d1 = datetime.strptime(str(admissao), formato)
    d2 = datetime.strptime(str(demissao), formato)
    verbas = {}
    
    sal_min = 1412.00
    adic_insal = 0
    if grau_insalubridade == "Mínimo (10%)": adic_insal = sal_min * 0.10
    elif grau_insalubridade == "Médio (20%)": adic_insal = sal_min * 0.20
    elif grau_insalubridade == "Máximo (40%)": adic_insal = sal_min * 0.40
    
    adic_peric = salario_base * 0.30 if tem_periculosidade else 0
    remuneracao = salario_base + max(adic_insal, adic_peric) 
    
    if adic_insal > 0: verbas["Adicional Insalubridade"] = adic_insal
    if adic_peric > 0: verbas["Adicional Periculosidade"] = adic_peric

    meses_trab = (d2.year - d1.year) * 12 + d2.month - d1.month
    anos_completos = meses_trab // 12
    verbas["Saldo Salário"] = (remuneracao/30) * d2.day
    
    dias_aviso = min(90, 30 + (3 * anos_completos))
    
    if motivo == "Demissão sem Justa Causa":
        if aviso_tipo == "Indenizado":
            verbas[f"Aviso Prévio ({dias_aviso} dias)"] = (remuneracao/30) * dias_aviso
            d2 = d2 + timedelta(days=dias_aviso)
    elif motivo == "Pedido de Demissão" and aviso_tipo == "Não Trabalhado":
        verbas["Desconto Aviso Prévio"] = -remuneracao

    meses_ano = d2.month
    if d2.day < 15: meses_ano -= 1
    if meses_ano == 0: meses_ano = 12

    if motivo != "Justa Causa":
        verbas[f"13º Proporcional ({meses_ano}/12)"] = (remuneracao/12) * meses_ano
        verbas[f"Férias Prop. ({meses_ano}/12) + 1/3"] = ((remuneracao/12) * meses_ano) * 1.3333
        if ferias_vencidas: verbas["Férias Vencidas + 1/3"] = remuneracao * 1.3333
        
    if motivo == "Demissão sem Justa Causa": verbas["Multa 40% FGTS"] = saldo_fgts * 0.4
    elif motivo == "Acordo": verbas["Multa 20% FGTS"] = saldo_fgts * 0.2
    
    return verbas

# ==========================================================
# 5. CSS VISUAL
# ==========================================================
def local_css():
    st.markdown("""<style>
        .stApp { background-color: #0e1117; color: white; }
        .stButton>button { border: 1px solid #00F3FF; color: #00F3FF; background: transparent; width: 100%; }
        .stButton>button:hover { background: #00F3FF; color: black; }
        h1, h2, h3 { color: #00F3FF !important; font-family: sans-serif; }
    </style>""", unsafe_allow_html=True)
local_css()

# ==========================================================
# 6. LOGIN & CADASTRO (BLINDADO v8.5)
# ==========================================================
if "logado" not in st.session_state: st.session_state.logado = False
if "usuario_atual" not in st.session_state: st.session_state.usuario_atual = ""

if not st.session_state.logado:
    col1, col2, col3 = st.columns([1, 1.2, 1])
    with col2:
        st.markdown("<br><h1 style='text-align: center; font-size: 4rem;'>🛡️</h1>", unsafe_allow_html=True)
        st.markdown("""<div style='text-align: center;'><h1 class='tech-header' style='font-size: 2.5rem;'>LEGALHUB ELITE</h1></div>""", unsafe_allow_html=True)

        if not CONEXAO_NUVEM: 
            st.error("⚠️ MODO OFFLINE: Configure os Secrets no Streamlit Cloud para salvar dados.")
        else: 
            st.success("☁️ CONEXÃO SEGURA ATIVA")
            
        with st.container(border=True):
            tab_login, tab_cadastro = st.tabs(["🔐 ENTRAR", "📝 CRIAR CONTA"])
            
            with tab_login:
                user_input = st.text_input("Usuário", key="login_user").strip().lower()
                pwd_input = st.text_input("Senha", type="password", key="login_pwd").strip()
                c_entrar, c_reset = st.columns(2)
                
                if c_entrar.button("LOGIN", use_container_width=True):
                    # Login de emergência offline
                    if not CONEXAO_NUVEM and user_input == 'admin' and pwd_input == 'admin':
                        st.session_state.logado = True
                        st.session_state.usuario_atual = 'admin'
                        st.session_state.plano_atual = 'full'
                        st.rerun()
                    
                    res = run_query("SELECT * FROM usuarios WHERE username = %s AND senha = %s", (user_input, pwd_input), return_data=True)
                    if res is not None and not res.empty:
                        st.session_state.logado = True
                        st.session_state.usuario_atual = user_input
                        st.session_state.escritorio_atual = res.iloc[0]['escritorio']
                        st.session_state.plano_atual = res.iloc[0]['plano']
                        st.rerun()
                    else:
                        st.error("Usuário ou senha incorretos.")
                
                if c_reset.button("🆘 Reset Admin", use_container_width=True):
                    if run_query("INSERT INTO usuarios (username, senha, escritorio, email_oab, creditos, plano) VALUES ('admin', 'admin', 'Master Office', 'adm@lh.com', 9999, 'full') ON CONFLICT (username) DO UPDATE SET senha = 'admin'"):
                        st.success("Admin resetado! Use: admin / admin")
                    else: st.error("Erro ao resetar.")

            with tab_cadastro:
                new_user = st.text_input("Novo Usuário", key="cad_user").strip().lower()
                new_pwd = st.text_input("Nova Senha", type="password", key="cad_pwd").strip()
                new_office = st.text_input("Nome do Escritório", key="cad_office")
                
                if st.button("CADASTRAR", use_container_width=True):
                    if not CONEXAO_NUVEM:
                        st.error("Não é possível cadastrar no modo Offline.")
                    elif new_user and new_pwd and new_office:
                        check = run_query("SELECT * FROM usuarios WHERE username = %s", (new_user,), return_data=True)
                        if check is not None and not check.empty:
                            st.error("⚠️ Usuário já existe!")
                        else:
                            ok = run_query("INSERT INTO usuarios (username, senha, escritorio, creditos, plano) VALUES (%s, %s, %s, 10, 'starter')", (new_user, new_pwd, new_office))
                            if ok:
                                st.success(f"✅ Cadastro realizado! Faça login na aba ENTRAR.")
                            else:
                                st.error("❌ Erro ao salvar no banco. Verifique requirements.txt")
                    else:
                        st.warning("Preencha todos os campos.")
        st.markdown("<div style='text-align:center; margin-top:10px; color: #475569;'>SYSTEM V8.5 // SECURE</div>", unsafe_allow_html=True)
    st.stop()

# ==========================================================
# 7. APLICAÇÃO PRINCIPAL
# ==========================================================
if "GOOGLE_API_KEY" in st.secrets: api_key = st.secrets["GOOGLE_API_KEY"]
else: api_key = st.text_input("🔑 API Key:", type="password", key="sidebar_api_key")

df_user = run_query("SELECT creditos, plano FROM usuarios WHERE username = %s", (st.session_state.usuario_atual,), return_data=True)
if df_user is not None and not df_user.empty:
    creditos_atuais = df_user.iloc[0]['creditos']
    st.session_state.plano_atual = df_user.iloc[0]['plano']
else: creditos_atuais = 0

with st.sidebar:
    st.title("🛡️ MENU")
    st.caption(f"Logado: {st.session_state.usuario_atual}")
    
    if "navegacao_override" not in st.session_state: st.session_state.navegacao_override = None
    
    mapa_nav = {"Dashboard": "📊 Dashboard", "Redator IA": "✍️ Redator Jurídico", "Contratos": "📜 Contratos", "Calculos": "🧮 Cálculos Jurídicos", "Audiência": "🏛️ Estratégia de Audiência", "Gestão Casos": "📂 Gestão de Casos", "Monitor Prazos": "🚦 Monitor de Prazos", "Assinatura": "💎 Planos & Upgrade"}
    opcoes_menu = list(mapa_nav.keys())
    idx_radio = 0
    if st.session_state.get("navegacao_override"):
        try: idx_radio = opcoes_menu.index([k for k, v in mapa_nav.items() if v == st.session_state.navegacao_override][0])
        except: pass
        st.session_state.navegacao_override = None
    escolha_menu = st.radio("Menu Navegação", options=opcoes_menu, index=idx_radio, horizontal=True, label_visibility="collapsed")
    menu_opcao = mapa_nav[escolha_menu]

    st.divider()
    with st.expander("⚙️ ADMIN"):
        novo_plano = st.selectbox("Mudar Plano", ["starter", "full", "criminal", "trabalhista", "civil"])
        if st.button("Atualizar"):
            run_query("UPDATE usuarios SET plano = %s WHERE username = %s", (novo_plano, st.session_state.usuario_atual))
            st.rerun()
            
    st.markdown("<h4 style='font-size:1rem;'>CRÉDITOS</h4>", unsafe_allow_html=True)
    st.progress(min(creditos_atuais/100, 1.0))
    if st.button("LOGOUT"): st.session_state.logado = False; st.rerun()

# --- TELAS ---

if menu_opcao == "📊 Dashboard":
    st.header("📊 Visão Geral")
    c1, c2 = st.columns(2)
    docs = run_query("SELECT count(*) FROM documentos WHERE escritorio = %s", (st.session_state.escritorio_atual,), return_data=True)
    qtd = docs.iloc[0][0] if docs is not None else 0
    c1.metric("Documentos", qtd)
    c2.metric("Plano", st.session_state.plano_atual.upper())
    
    st.subheader("Acesso Rápido")
    c1, c2 = st.columns(2)
    if c1.button("Nova Petição"): st.session_state.navegacao_override = "✍️ Redator Jurídico"; st.rerun()
    if c2.button("Novo Cálculo"): st.session_state.navegacao_override = "🧮 Cálculos Jurídicos"; st.rerun()

# === REDATOR IA TURBINADO (SUAS LISTAS ESPECÍFICAS) ===
elif menu_opcao == "✍️ Redator Jurídico":
    st.header("✍️ Redator IA (Anti-Alucinação)")
    area = st.selectbox("Área", ["Cível", "Trabalhista", "Criminal", "Tributário", "Previdenciário"])
    
    pecas = []
    if area == "Cível": 
        pecas = ["Petição Inicial", "Contestação", "Réplica", "Reconvenção", "Ação Rescisória", "Mandado de Segurança", "Ação Civil Pública", "Embargos à Execução", "Embargos de Terceiro", "Exceção de Incompetência", "Impugnação ao Valor da Causa", "Pedido de Tutela", "Impugnação ao Cumprimento", "Apelação", "Agravo de Instrumento", "Embargos de Declaração", "Recurso Especial", "Recurso Extraordinário"]
    elif area == "Trabalhista": 
        pecas = ["Reclamação Trabalhista", "Contestação", "Reconvenção", "Exceção de Incompetência", "Impugnação ao Valor", "Recurso Ordinário", "Recurso de Revista", "Embargos (TST)", "Agravo de Instrumento", "Agravo de Petição", "Embargos à Execução", "Consignação em Pagamento"]
    elif area == "Criminal": 
        pecas = ["Resposta à Acusação", "Memoriais", "Queixa-Crime", "Defesa Preliminar (Drogas)", "Apelação", "RSE", "Agravo em Execução", "Embargos de Declaração", "Recurso Especial", "Recurso Extraordinário", "ROC", "Habeas Corpus", "Revisão Criminal", "Pedido de Liberdade", "Relaxamento de Prisão", "Restituição de Coisas", "Representação"]
    elif area == "Tributário": 
        pecas = ["Declaratória de Inexistência", "Anulatória de Débito", "Repetição de Indébito", "Mandado de Segurança", "Consignação em Pagamento", "Embargos à Execução Fiscal", "Exceção de Pré-Executividade", "Apelação", "Agravo", "Recurso Especial", "Defesa Administrativa", "Recurso Administrativo"]
    elif area == "Previdenciário": 
        pecas = ["Requerimento Administrativo", "Petição Inicial Administrativa", "Recurso Administrativo", "Petição de Juntada", "Petição Inicial Judicial", "Contestação", "Réplica", "Recurso Inominado", "Apelação", "Pedido de Tutela", "Cumprimento de Sentença"]
    
    tipo = st.selectbox("Peça", pecas)
    c1, c2 = st.columns(2)
    cli = c1.text_input("Cliente")
    adv = c2.text_input("Parte Contrária")
    fatos = st.text_area("Fatos", height=150)
    busca_real = st.checkbox("🔍 Buscar Jurisprudência Real (STF/STJ/TST)", value=True)
    
    if st.button("GERAR PEÇA"):
        if fatos and cli:
            with st.spinner("Pesquisando e Redigindo..."):
                ctx = ""
                if busca_real: ctx = buscar_contexto_juridico(f"{tipo} {fatos}", area)
                
                prompt = f"Advogado {area}. Redija {tipo}. Cliente: {cli} vs {adv}. Fatos: {fatos}. {ctx}. Cite leis e jurisprudência se houver."
                res = tentar_gerar_conteudo(prompt, api_key)
                st.markdown(res)
                if "❌" not in res:
                    st.download_button("Baixar DOCX", gerar_word(res), f"{tipo}.docx")
                    run_query("INSERT INTO documentos (escritorio, data_criacao, cliente, area, tipo, conteudo) VALUES (%s, %s, %s, %s, %s, %s)", 
                             (st.session_state.escritorio_atual, str(date.today()), cli, area, tipo, res))

elif menu_opcao == "📜 Contratos":
    st.header("📜 Fábrica de Contratos")
    c1, c2 = st.columns(2)
    cli = c1.text_input("Contratante")
    cpf = c2.text_input("CPF/CNPJ")
    obj = st.text_area("Objeto")
    val = st.number_input("Valor", step=100.0)
    if st.button("GERAR CONTRATO"):
        res = tentar_gerar_conteudo(f"Contrato honorários. Cliente {cli}, CPF {cpf}. Objeto: {obj}. Valor R$ {val}. Contratado: {st.session_state.escritorio_atual}", api_key)
        st.markdown(res)
        st.download_button("Baixar", gerar_word(res), "Contrato.docx")

# === CALCULADORA UNIFICADA COMPLETA (V8.4) ===
elif menu_opcao == "🧮 Cálculos Jurídicos":
    st.header("🧮 Calculadoras Jurídicas")
    area_calc = st.selectbox("Área", ["Trabalhista (CLT)", "Cível (Art. 292/Liquidação)", "Família", "Tributária", "Criminal"])
    st.markdown("---")

    if area_calc == "Trabalhista (CLT)":
        st.subheader("Rescisão CLT + Adicionais")
        c1, c2, c3 = st.columns(3)
        adm = c1.date_input("Admissão", date(2022,1,1))
        dem = c2.date_input("Demissão", date.today())
        motivo = c3.selectbox("Motivo", ["Demissão sem Justa Causa", "Pedido de Demissão", "Justa Causa"])
        
        c4, c5, c6 = st.columns(3)
        sal = c4.number_input("Salário", value=2000.0)
        fgts = c5.number_input("Saldo FGTS", value=0.0)
        aviso = c6.selectbox("Aviso Prévio", ["Indenizado", "Trabalhado"])
        
        c7, c8 = st.columns(2)
        insal = c7.selectbox("Insalubridade", ["Não", "Mínimo (10%)", "Médio (20%)", "Máximo (40%)"])
        peric = c8.checkbox("Periculosidade (30%)")
        
        if st.button("CALCULAR TRABALHISTA"):
            if dem > adm:
                v = calcular_rescisao_completa(adm, dem, sal, motivo, fgts, False, aviso, insal, peric)
                st.table(pd.DataFrame(list(v.items()), columns=["Verba", "Valor"]))
                st.success(f"Total: R$ {sum(v.values()):,.2f}")

    elif area_calc == "Cível (Art. 292/Liquidação)":
        tab1, tab2, tab3 = st.tabs(["Liquidação de Sentença", "Valor da Causa", "Revisão Bancária"])
        
        with tab1: # Liquidação
            st.info("Atualização + Juros + Multa Art. 523 + Honorários")
            c1, c2 = st.columns(2)
            val = c1.number_input("Valor Condenação")
            idx = c2.number_input("Índice Correção", value=1.0)
            c3, c4 = st.columns(2)
            juros = c3.selectbox("Juros", ["1% a.m.", "Selic", "Sem"])
            meses = c4.number_input("Meses", value=12)
            
            c5, c6 = st.columns(2)
            multa = c5.checkbox("Multa Art. 523 (10%)")
            hon = c6.checkbox("Honorários Execução (10%)")
            
            if st.button("LIQUIDAR"):
                res = val * idx
                val_juros = 0
                if juros == "1% a.m.": val_juros = res * (0.01 * meses)
                elif juros == "Selic": val_juros = res * 0.12 # Est
                
                subtotal = res + val_juros
                total = subtotal + (subtotal*0.1 if multa else 0) + (subtotal*0.1 if hon else 0)
                st.success(f"Total Execução: R$ {total:,.2f}")
        
        with tab2: # Valor da Causa
            st.info("Art. 292 CPC")
            tipo = st.radio("Ação", ["Cobrança", "Alimentos", "Indenização"])
            if tipo == "Alimentos":
                m = st.number_input("Mensalidade")
                st.metric("Valor (12x)", f"R$ {m*12:,.2f}")
            elif tipo == "Cobrança":
                p = st.number_input("Principal")
                j = st.number_input("Juros Vencidos")
                m = st.number_input("Multas")
                st.metric("Valor Causa", f"R$ {p+j+m:,.2f}")
            else:
                d = st.number_input("Valor Pretendido")
                st.metric("Valor Causa", f"R$ {d:,.2f}")

        with tab3: # Revisão
            emp = st.number_input("Empréstimo")
            tx = st.number_input("Taxa %")
            m = st.number_input("Meses", value=12)
            if st.button("SIMULAR"):
                price = emp * ((tx/100) * (1 + tx/100)**m) / ((1 + tx/100)**m - 1)
                st.warning(f"Parcela Price: R$ {price:.2f} | Gauss (Est.): R$ {price*0.8:.2f}")

    elif area_calc == "Família":
        renda = st.number_input("Renda Líquida")
        f = st.slider("Filhos", 1, 5)
        if st.button("SUGERIR PENSÃO"): st.info(f"Sugerido: R$ {renda * (0.3 + (f-1)*0.05):,.2f}")

    elif area_calc == "Tributária":
        p = st.number_input("Tributo")
        m = st.number_input("Multa %")
        if st.button("ATUALIZAR TRIBUTO"): st.metric("Total", f"R$ {p * (1+m/100):,.2f}")

    elif area_calc == "Criminal":
        p_min = st.number_input("Pena Mínima")
        p_max = st.number_input("Pena Máxima")
        c = st.slider("Circunstâncias Ruins", 0, 8)
        if st.button("CALCULAR PENA"): st.error(f"Base: {p_min + ((p_max-p_min)/8 * c):.1f} anos")

elif menu_opcao == "📂 Gestão de Casos":
    st.header("📂 Cofre Digital")
    df = run_query("SELECT * FROM documentos WHERE escritorio = %s ORDER BY id DESC", (st.session_state.escritorio_atual,), return_data=True)
    if df is not None and not df.empty:
        for i, row in df.iterrows():
            with st.expander(f"{row['tipo']} - {row['cliente']}"):
                st.write(row['conteudo'][:200])
                st.download_button("Baixar", gerar_word(row['conteudo']), "Doc.docx", key=f"d{i}")
                if st.button("Excluir", key=f"x{i}"):
                    run_query("DELETE FROM documentos WHERE id = %s", (row['id'],))
                    st.rerun()
    else: st.info("Cofre vazio.")

elif menu == "Audiência":
    st.header("🏛️ Simulador de Audiência")
    st.info("Em breve: Simulação de perguntas cruzadas com IA.")

st.markdown("---")
st.markdown("<center>🔒 LEGALHUB ELITE v8.5 | POSTGRESQL SECURE</center>", unsafe_allow_html=True)
