import streamlit as st
import google.generativeai as genai
from pypdf import PdfReader
from docx import Document
from io import BytesIO
from duckduckgo_search import DDGS
from datetime import datetime, timedelta, date
import time
import pandas as pd
import base64
import sys
import socket
from urllib.parse import urlparse

# ==========================================================
# 1. SETUP INICIAL
# ==========================================================
try:
    import psycopg2
    LIB_OK = True
except ImportError:
    LIB_OK = False
    psycopg2 = None

st.set_page_config(
    page_title="LegalHub Elite v8.9", 
    page_icon="⚖️", 
    layout="wide",
    initial_sidebar_state="expanded"
)

# Verifica Secrets
try:
    DB_URI = st.secrets["DB_URI"]
    API_KEY_FIXA = st.secrets["GOOGLE_API_KEY"]
    SECRETS_OK = True
except:
    DB_URI = ""
    API_KEY_FIXA = ""
    SECRETS_OK = False

CONEXAO_NUVEM = (LIB_OK and SECRETS_OK)

# ==========================================================
# 2. CONEXÃO COM BANCO (COM "HACK" DE IPv4)
# ==========================================================
def get_ipv4_connection_string(uri):
    """
    Função Hacker: Força a resolução DNS para IPv4
    para evitar o erro 'Cannot assign requested address' no Streamlit Cloud.
    """
    try:
        parsed = urlparse(uri)
        hostname = parsed.hostname
        # Resolve o nome para um IP numérico (IPv4)
        ipv4 = socket.gethostbyname(hostname)
        # Substitui o nome pelo IP na string de conexão
        new_uri = uri.replace(hostname, ipv4)
        return new_uri
    except Exception as e:
        # Se falhar, retorna o original e torce para funcionar
        return uri

def get_db_connection():
    if CONEXAO_NUVEM:
        try:
            # Tenta conexão normal
            return psycopg2.connect(DB_URI, sslmode='require')
        except Exception as e_ipv6:
            try:
                # Se falhar, tenta o Hack IPv4
                uri_ipv4 = get_ipv4_connection_string(DB_URI)
                return psycopg2.connect(uri_ipv4, sslmode='require')
            except Exception as e_final:
                st.toast(f"Erro Fatal Conexão: {e_final}", icon="❌")
                return None
    else:
        import sqlite3
        return sqlite3.connect(':memory:', check_same_thread=False)

def run_query(query, params=(), return_data=False):
    conn = get_db_connection()
    if conn is None: return None
    try:
        c = conn.cursor()
        if not CONEXAO_NUVEM: query = query.replace('%s', '?')
        
        c.execute(query, params)
        
        if return_data:
            data = c.fetchall()
            if c.description:
                col_names = [desc[0] for desc in c.description]
                conn.close()
                return pd.DataFrame(data, columns=col_names)
            else:
                conn.close()
                return None
        else:
            conn.commit()
            conn.close()
            return True
    except Exception as e:
        if conn: conn.close()
        st.error(f"ERRO SQL: {e}")
        return None

# --- CRIAÇÃO AUTOMÁTICA (TENTATIVA SILENCIOSA) ---
if CONEXAO_NUVEM:
    try:
        run_query("CREATE TABLE IF NOT EXISTS usuarios (username TEXT PRIMARY KEY, senha TEXT, escritorio TEXT, email_oab TEXT, creditos INTEGER DEFAULT 10, plano TEXT DEFAULT 'starter')")
        run_query("CREATE TABLE IF NOT EXISTS documentos (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, escritorio TEXT, data_criacao TEXT, cliente TEXT, area TEXT, tipo TEXT, conteudo TEXT)")
    except: pass

# ==========================================================
# 3. FUNÇÕES GERAIS (MANTENDO TUDO)
# ==========================================================
def get_base64_of_bin_file(bin_file):
    try:
        with open(bin_file, 'rb') as f: data = f.read()
        return base64.b64encode(data).decode()
    except: return None

def gerar_word(texto):
    doc = Document(); 
    for p in texto.split('\n'): 
        if p.strip(): doc.add_paragraph(p)
    buf = BytesIO(); doc.save(buf); buf.seek(0)
    return buf

def extrair_texto_pdf(arquivo):
    try: return "".join([p.extract_text() for p in PdfReader(arquivo).pages])
    except: return ""

def buscar_contexto_juridico(tema, area):
    fontes = {"Criminal": "site:stj.jus.br", "Trabalhista": "site:tst.jus.br", "Cível": "site:stj.jus.br"}
    query = f"{tema} jurisprudência {fontes.get(area, 'site:jusbrasil.com.br')}"
    try:
        with DDGS() as ddgs:
            res = list(ddgs.text(query, region="br-pt", max_results=3))
            if res: return "\n\n[JURISPRUDÊNCIA]:\n" + "\n".join([f"- {r['body']}" for r in res])
    except: pass
    return ""

def tentar_gerar_conteudo(prompt, api_key_val):
    chave = api_key_val if api_key_val else API_KEY_FIXA
    if not chave: return "⚠️ Configure a API Key."
    genai.configure(api_key=chave)
    try:
        return genai.GenerativeModel("gemini-1.5-flash").generate_content(prompt).text
    except Exception as e: return f"❌ Erro IA: {e}"

def calcular_rescisao_completa(admissao, demissao, salario, motivo, saldo_fgts, ferias_venc, aviso, insal, peric):
    verbas = {}
    base = salario
    if peric: base += salario * 0.3
    if insal == "Mínimo": base += 1412 * 0.1
    elif insal == "Médio": base += 1412 * 0.2
    elif insal == "Máximo": base += 1412 * 0.4
    
    d1 = datetime.strptime(str(admissao), "%Y-%m-%d")
    d2 = datetime.strptime(str(demissao), "%Y-%m-%d")
    
    verbas["Saldo Salário"] = (base/30) * d2.day
    meses = (d2.year - d1.year) * 12 + d2.month - d1.month
    
    if motivo == "Demissão sem Justa Causa":
        verbas["Multa 40% FGTS"] = saldo_fgts * 0.4
        aviso_dias = min(90, 30 + (3 * (meses//12)))
        if aviso == "Indenizado": verbas[f"Aviso ({aviso_dias}d)"] = (base/30)*aviso_dias
    return verbas

# --- CSS ---
def local_css():
    st.markdown("""<style>
        .stApp { background-color: #0e1117; color: white; }
        .stButton>button { border: 1px solid #00F3FF; color: #00F3FF; background: transparent; width: 100%; }
        h1, h2 { color: #00F3FF !important; }
    </style>""", unsafe_allow_html=True)
local_css()

# ==========================================================
# 4. LOGIN (COM REPARO E CORREÇÃO DE REDE)
# ==========================================================
if "logado" not in st.session_state: st.session_state.logado = False
if "usuario_atual" not in st.session_state: st.session_state.usuario_atual = ""

if not st.session_state.logado:
    col1, col2, col3 = st.columns([1, 1.2, 1])
    with col2:
        st.markdown("<br><h1 style='text-align: center;'>🛡️ LEGALHUB</h1>", unsafe_allow_html=True)
        
        if CONEXAO_NUVEM:
             st.success("☁️ CONEXÃO SEGURA (IPv4 Patch Ativo)")
        else:
             st.warning("⚠️ MODO OFFLINE")

        with st.container(border=True):
            tab1, tab2, tab3 = st.tabs(["ENTRAR", "CADASTRAR", "🔧 SUPORTE"])
            
            with tab1:
                u = st.text_input("Usuário", key="u").strip().lower()
                p = st.text_input("Senha", type="password", key="p").strip()
                if st.button("LOGIN", use_container_width=True):
                    res = run_query("SELECT * FROM usuarios WHERE username = %s AND senha = %s", (u, p), return_data=True)
                    if res is not None and not res.empty:
                        st.session_state.logado = True
                        st.session_state.usuario_atual = u
                        st.session_state.escritorio_atual = res.iloc[0]['escritorio']
                        st.session_state.plano_atual = res.iloc[0]['plano']
                        st.rerun()
                    else: st.error("Dados inválidos ou usuário inexistente.")
                
                if st.button("🆘 Resetar Admin"):
                    if run_query("INSERT INTO usuarios (username, senha, escritorio, email_oab, creditos, plano) VALUES ('admin', 'admin', 'Master Office', 'adm@lh.com', 9999, 'full') ON CONFLICT (username) DO UPDATE SET senha='admin'"):
                        st.success("Admin resetado! Use: admin / admin")
                    else:
                        st.error("Falha ao resetar. Tente a aba SUPORTE.")
            
            with tab2:
                nu = st.text_input("Novo Usuário").strip().lower()
                np = st.text_input("Nova Senha").strip()
                ne = st.text_input("Escritório")
                if st.button("CADASTRAR", use_container_width=True):
                    if run_query("INSERT INTO usuarios (username, senha, escritorio, creditos, plano) VALUES (%s, %s, %s, 10, 'starter')", (nu, np, ne)):
                        st.success("Sucesso! Faça login.")
                    else: st.error("Erro ao salvar. Verifique se usuário já existe.")

            with tab3:
                st.warning("Se estiver vendo erros de conexão, clique abaixo.")
                if st.button("🛠️ REPARAR BANCO DE DADOS (RESET TOTAL)", use_container_width=True):
                    with st.spinner("Aplicando correção de rede e limpando tabelas..."):
                        run_query("DROP TABLE IF EXISTS usuarios")
                        run_query("DROP TABLE IF EXISTS documentos")
                        run_query("CREATE TABLE usuarios (username TEXT PRIMARY KEY, senha TEXT, escritorio TEXT, email_oab TEXT, creditos INTEGER DEFAULT 10, plano TEXT DEFAULT 'starter')")
                        run_query("CREATE TABLE documentos (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, escritorio TEXT, data_criacao TEXT, cliente TEXT, area TEXT, tipo TEXT, conteudo TEXT)")
                        run_query("INSERT INTO usuarios (username, senha, escritorio, creditos, plano) VALUES ('admin', 'admin', 'Master Office', 9999, 'full')")
                        st.success("Banco reparado! Tente logar com admin/admin.")
    st.stop()

# ==========================================================
# 5. SISTEMA PRINCIPAL
# ==========================================================
df_user = run_query("SELECT creditos, plano FROM usuarios WHERE username = %s", (st.session_state.usuario_atual,), return_data=True)
creditos = df_user.iloc[0]['creditos'] if df_user is not None else 0
plano = st.session_state.plano_atual = df_user.iloc[0]['plano'] if df_user is not None else "starter"

with st.sidebar:
    st.title("MENU")
    st.caption(f"User: {st.session_state.usuario_atual}")
    
    if "navegacao_override" not in st.session_state: st.session_state.navegacao_override = None
    mapa = {"Dashboard": "📊 Dashboard", "Redator": "✍️ Redator Jurídico", "Calculos": "🧮 Cálculos", "Contratos": "📜 Contratos", "Cofre": "📂 Cofre"}
    
    idx = 0
    if st.session_state.navegacao_override:
        try: idx = list(mapa.values()).index(st.session_state.navegacao_override)
        except: pass
        st.session_state.navegacao_override = None
        
    escolha = st.radio("Navegar", list(mapa.keys()), index=idx)
    menu = mapa[escolha]
    
    st.divider()
    if st.session_state.usuario_atual == 'admin':
        with st.expander("⚙️ ADMIN"):
            all_users = run_query("SELECT username, plano FROM usuarios", return_data=True)
            if all_users is not None: st.dataframe(all_users)
            
            user_to_edit = st.selectbox("Usuário", all_users['username'].unique() if all_users is not None else [])
            new_plan = st.selectbox("Novo Plano", ["starter", "full"])
            if st.button("Salvar Plano"):
                run_query("UPDATE usuarios SET plano = %s WHERE username = %s", (new_plan, user_to_edit))
                st.success("Atualizado!")
                time.sleep(1); st.rerun()

    if st.button("SAIR"): st.session_state.logado = False; st.rerun()

# --- TELAS ---
if menu == "📊 Dashboard":
    st.header("📊 Visão Geral")
    docs = run_query("SELECT count(*) FROM documentos WHERE escritorio = %s", (st.session_state.escritorio_atual,), return_data=True)
    c1, c2 = st.columns(2)
    c1.metric("Documentos", docs.iloc[0][0] if docs is not None else 0)
    c2.metric("Plano", plano.upper())
    
    st.markdown("### Acesso Rápido")
    c1, c2 = st.columns(2)
    if c1.button("Nova Peça"): st.session_state.navegacao_override = "✍️ Redator Jurídico"; st.rerun()
    if c2.button("Novo Cálculo"): st.session_state.navegacao_override = "🧮 Cálculos"; st.rerun()

elif menu == "✍️ Redator Jurídico":
    st.header("✍️ Redator IA (Anti-Alucinação)")
    area = st.selectbox("Área", ["Cível", "Trabalhista", "Criminal", "Tributário", "Previdenciário"])
    pecas = ["Petição Inicial", "Contestação", "Réplica", "Recurso", "Habeas Corpus", "Mandado de Segurança", "Reclamação Trabalhista"]
    tipo = st.selectbox("Peça", pecas)
    c1, c2 = st.columns(2)
    cli = c1.text_input("Cliente")
    fatos = st.text_area("Fatos")
    if st.button("GERAR"):
        with st.spinner("Redigindo..."):
            ctx = buscar_contexto_juridico(f"{tipo} {fatos}", area)
            res = tentar_gerar_conteudo(f"Advogado {area}. Redija {tipo}. Cliente: {cli}. Fatos: {fatos}. {ctx}", api_key)
            st.markdown(res)
            if "❌" not in res:
                run_query("INSERT INTO documentos (escritorio, data_criacao, cliente, area, tipo, conteudo) VALUES (%s, %s, %s, %s, %s, %s)", 
                         (st.session_state.escritorio_atual, str(date.today()), cli, area, tipo, res))
                st.download_button("Baixar", gerar_word(res), "Peca.docx")

elif menu == "🧮 Cálculos":
    st.header("🧮 Central de Cálculos")
    mod = st.selectbox("Módulo", ["Trabalhista", "Cível (Liquidação)", "Família", "Tributária"])
    
    if mod == "Trabalhista":
        st.info("Rescisão CLT")
        c1, c2 = st.columns(2)
        adm = c1.date_input("Admissão", date(2022,1,1))
        dem = c2.date_input("Demissão")
        sal = st.number_input("Salário")
        motivo = st.selectbox("Motivo", ["Demissão sem Justa Causa", "Pedido Demissão"])
        if st.button("Calcular"):
            v = calcular_rescisao_completa(adm, dem, sal, motivo, 0, False, "Indenizado", "Não", False)
            st.dataframe(pd.DataFrame(list(v.items()), columns=["Verba", "Valor"]))
            
    elif mod == "Cível (Liquidação)":
        st.info("Liquidação de Sentença + Art 523")
        val = st.number_input("Valor Condenação")
        idx = st.number_input("Índice Correção", 1.0)
        multa = st.checkbox("Multa 10%")
        hon = st.checkbox("Honorários 10%")
        if st.button("Liquidar"):
            total = val * idx
            if multa: total += total * 0.1
            if hon: total += total * 0.1
            st.success(f"Total: R$ {total:,.2f}")

    elif mod == "Família":
        st.info("Pensão Alimentícia")
        r = st.number_input("Renda")
        f = st.slider("Filhos", 1, 5)
        if st.button("Calcular"): st.success(f"Sugerido: R$ {r * (0.3 + (f-1)*0.05):,.2f}")

elif menu == "📜 Contratos":
    st.header("Gerador de Contratos")
    cli = st.text_input("Cliente")
    if st.button("Gerar"):
        res = tentar_gerar_conteudo(f"Contrato honorários para {cli}", api_key)
        st.markdown(res)

elif menu == "📂 Cofre":
    st.header("Cofre Digital")
    df = run_query("SELECT * FROM documentos WHERE escritorio = %s ORDER BY id DESC", (st.session_state.escritorio_atual,), return_data=True)
    if df is not None:
        for i, row in df.iterrows():
            with st.expander(f"{row['tipo']} - {row['cliente']}"):
                st.write(row['conteudo'][:200])
                st.download_button("Baixar", gerar_word(row['conteudo']), "Doc.docx", key=f"d{i}")
